//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovay
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние накладной.
    /// </summary>
    // *** Start programmer edit section *** (СостояниеНакладной CustomAttributes)

    // *** End programmer edit section *** (СостояниеНакладной CustomAttributes)
    public enum СостояниеНакладной
    {
        
        // *** Start programmer edit section *** (СостояниеНакладной.Отгруженная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Отгруженная CustomAttributes)
        [Caption("Отгруженная")]
        Отгруженная,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Готовая CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Готовая CustomAttributes)
        [Caption("Готовая")]
        Готовая,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Новая CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Новая CustomAttributes)
        [Caption("Новая")]
        Новая,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Выписанная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Выписанная CustomAttributes)
        [Caption("Выписанная")]
        Выписанная,
        
        // *** Start programmer edit section *** (СостояниеНакладной.Приостановленная CustomAttributes)

        // *** End programmer edit section *** (СостояниеНакладной.Приостановленная CustomAttributes)
        [Caption("Приостановленная")]
        Приостановленная,
    }
}
