//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovay
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Хранилище.
    /// </summary>
    // *** Start programmer edit section *** (Хранилище CustomAttributes)

    // *** End programmer edit section *** (Хранилище CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ХранилищеE", new string[] {
            "КодАдреса as \'Код адреса\'",
            "Склад as \'Склад\'",
            "Склад.Адрес as \'Адрес\'"}, Hidden=new string[] {
            "Склад.Адрес"})]
    [MasterViewDefineAttribute("ХранилищеE", "Склад", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [View("ХранилищеL", new string[] {
            "КодАдреса as \'Код адреса\'",
            "Склад.Адрес as \'Адрес\'"})]
    public class Хранилище : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодАдреса;
        
        private IIS.Kursovay.Склад fСклад;
        
        // *** Start programmer edit section *** (Хранилище CustomMembers)

        // *** End programmer edit section *** (Хранилище CustomMembers)

        
        /// <summary>
        /// КодАдреса.
        /// </summary>
        // *** Start programmer edit section *** (Хранилище.КодАдреса CustomAttributes)

        // *** End programmer edit section *** (Хранилище.КодАдреса CustomAttributes)
        public virtual int КодАдреса
        {
            get
            {
                // *** Start programmer edit section *** (Хранилище.КодАдреса Get start)

                // *** End programmer edit section *** (Хранилище.КодАдреса Get start)
                int result = this.fКодАдреса;
                // *** Start programmer edit section *** (Хранилище.КодАдреса Get end)

                // *** End programmer edit section *** (Хранилище.КодАдреса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Хранилище.КодАдреса Set start)

                // *** End programmer edit section *** (Хранилище.КодАдреса Set start)
                this.fКодАдреса = value;
                // *** Start programmer edit section *** (Хранилище.КодАдреса Set end)

                // *** End programmer edit section *** (Хранилище.КодАдреса Set end)
            }
        }
        
        /// <summary>
        /// Хранилище.
        /// </summary>
        // *** Start programmer edit section *** (Хранилище.Склад CustomAttributes)

        // *** End programmer edit section *** (Хранилище.Склад CustomAttributes)
        [PropertyStorage(new string[] {
                "Склад"})]
        [NotNull()]
        public virtual IIS.Kursovay.Склад Склад
        {
            get
            {
                // *** Start programmer edit section *** (Хранилище.Склад Get start)

                // *** End programmer edit section *** (Хранилище.Склад Get start)
                IIS.Kursovay.Склад result = this.fСклад;
                // *** Start programmer edit section *** (Хранилище.Склад Get end)

                // *** End programmer edit section *** (Хранилище.Склад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Хранилище.Склад Set start)

                // *** End programmer edit section *** (Хранилище.Склад Set start)
                this.fСклад = value;
                // *** Start programmer edit section *** (Хранилище.Склад Set end)

                // *** End programmer edit section *** (Хранилище.Склад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ХранилищеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ХранилищеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ХранилищеE", typeof(IIS.Kursovay.Хранилище));
                }
            }
            
            /// <summary>
            /// "ХранилищеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ХранилищеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ХранилищеL", typeof(IIS.Kursovay.Хранилище));
                }
            }
        }
    }
}
